/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'srikrishnavempati' at '11/27/14 1:28 AM' with Gradle 2.2
 *
 * @author srikrishnavempati, @date 11/27/14 1:28 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
